# Generated by Django 3.2 on 2023-05-17 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='comm',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.DeleteModel(
            name='Comments',
        ),
    ]
