# Generated by Django 3.2 on 2023-05-15 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20230515_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games',
            name='count_player',
            field=models.FloatField(),
        ),
    ]
