# Generated by Django 3.2 on 2023-06-08 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_company_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games',
            name='count_player',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='games',
            name='date_created',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='games',
            name='rating',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
